apiVersion: v1
kind: Secret
metadata:
  name: ctf-secrets
type: Opaque
stringData:
  # Local K8s Postgres Connection URL
  DATABASE_URL: "postgresql://postgres:localpassword@postgres-service:5432/ctfdb"
  # JWT Secret Key
  JWT_SECRET: "super-secret-key-for-siege-of-the-five-gates-ctf"
  # Redis connection URL (internal k8s service)
  REDIS_URL: "redis://redis-service:6379/0"
